name: Rust

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Release build
      run: cargo build --verbose --release
    - name: Run tests
      run: cargo test --verbose --release
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startswith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        draft: true
        files:
          README.md
          target/release/planner
          target/release/trainer
