name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v4
    - name: Install Python requirements
      run: pip install -r requirements.txt
    - name: Build release binary
      run: cargo build --bins --verbose --release
    - name: Rename binaries
      run: |
        mv target/release/planner planner-linux
        mv target/release/trainer trainer-linux
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startswith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        prerelease: true
        files: |
          planner-linux
          trainer-linux
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
