name: Release

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*.*.*"

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install Python requirements
      run: pip install -r requirements.txt
    - name: Release build
      run: |
        rustup component add rust-std-x86_64-unknown-linux-musl
        cargo build --verbose --bins --release --target x86_64-unknown-linux-musl
    - name: Release
      uses: softprops/action-gh-release@v2
      if: startswith(github.ref, 'refs/tags/')
      with:
        fail_on_unmatched_files: true
        prerelease: true
        files: |
          target/release/planner
          target/release/trainer
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
